////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[[apache-ofbiz]]
= Another bigfish ecommerce

This is an effort to make bigfish ecommerces modules to work with the latest Apache Ofbiz release.
Indeed the latests- bigfish ecommerce available to download works with Ofbiz 13 which is quite old.
Especially that Ofbiz now, uses gradle and plugins instead of ANT and hot deployed modules.
The ecommerce module is made multi lingual with arabic support. The css
The solr module has been taken from Ofbiz plugins. The code has been adapted to use that one instead of the one developed by Solveda.
Actually, the official SOLR plugin makes Apache SOLR integration more elegrant. Indexing is made through solrJ api instead of passing through a CSV file.



For more details about OFBiz please visit the OFBiz Documentation page:

http://ofbiz.apache.org/documentation.html[OFBiz documentation]

http://www.apache.org/licenses/LICENSE-2.0[OFBiz License]

for more detail about Solveda bigfish:

http://bigfish.solveda.com/bfDownload.html

The code by default uses postgreSQL DB. But this can be changed the ususal way in the entity framework module config.

A demo is avaialable here. The data given in solveda demo was recycled here.

http://webshop.tihamania.net

[[Acknowledgement]]
== Acknowledgement

We make here a special thanks to Solveda effort, and their will to make their code under Apache 2.0 license,
which allowed us to make use of their code.
That's why the produced code is made publicly avaiable with Apache license too.

[[Special notice]]
== Special notice
Bigfish base code make usage of deprecated methods which no longer exist. An effort was made to port them
to the new methods implementations.
We made osafe and osafe-admin as stand alone plugins that depend on the existing SOLR plugin.

=== Big fish XLS catalog
The catalog has been adapted to add extra columns for multi lingual translations AR/FR/NL.

=== Big fish admin module
Only services which made interest for us had a special attention from us, to make them functional like catalog Feeds import and Solr indexing. We are not sure that other functions are ok.

=== Inventory management
We added the implementation of inventory managemetn using Ofbiz method. Hence, products inventory can be received through the Facility module in Ofbiz.
Actually, we wanted to administer the sales through the OOTB  Ofbiz modules instead of big fish admin module which manages the invetory through product attributes.